name: bottomless
version: 1.0.0
github: "andreythegeek/bottomless"
license: Apache-2.0
author: "Andrey Petrov"
maintainer: "andrey@petrov.works"
copyright: "2020 Andrey Petrov"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis: TOML Parser
category: TOML
description: Read data from TOML files

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  bottomless-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - bottomless
